apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cpfull-1778507898
  description: "Full E2E demo: GitHub repo to AWS CodePipeline to CodeBuild to ArgoCD to K8s pod"
  annotations:
    github.com/project-slug: priyankaajbhagatt-collab/cpfull-1778507898
    backstage.io/techdocs-ref: dir:.
    argocd/app-selector: service=cpfull-1778507898
    backstage.io/kubernetes-label-selector: app=cpfull-1778507898
    aws.amazon.com/aws-codepipeline-tags: Service=cpfull-1778507898
  tags:
    - java
    - spring-boot
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  system: devex-scaffolder
