apiVersion: v1
kind: Service
metadata:
  name: cpfull-1778507898
  labels:
    app: cpfull-1778507898
    market: usa
    managed-by: backstage-scaffolder
spec:
  selector:
    app: cpfull-1778507898
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
